In [156]:
A = [2,11,3,5,13,7,19,17,23]
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
a = np.array(A)
b = np.ediff1d(a)
c =[]
for i in range(len(a)-2):
    if a[i]<a[i+1]<a[i+2]:
        c.append(a[i])
        c.append(a[i+2])
    else:
        continue
c = np.array(c)
for el in c:
    print np.where(a == el)[0]

[2]
[4]


In [176]:
size = int(input('Enter the size of the list'))
a = np.random.randint(100, size=size)
print a
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
b = np.ediff1d(a)
b = np.append(b,0)
print b
c =[]
for i in range(len(a)):
    if b[i] < 0:
        c.append(a[i])    
    else:
        continue
print c
d=[]
for el in c:
    print np.where(a == el)[0]

Enter the size of the list10
[30 31 68 22 90 69 28 75 66 13]
[  1  37 -46  68 -21 -41  47  -9 -53   0]
[68, 90, 69, 75, 66]
[2]
[4]
[5]
[7]
[8]


In [177]:
df1 = pd.DataFrame(a)
df2 = pd.DataFrame(b)
df = pd.concat([df1,df2], ignore_index=True, axis = 1)
df.columns = ['values','diff']
df = df.fillna(0)
df

values  diff
0      30     1
1      31    37
2      68   -46
3      22    68
4      90   -21
5      69   -41
6      28    47
7      75    -9
8      66   -53
9      13     0

In [168]:
a[:3]

array([28, 34, 78])